image:
  name: traefik
  tag: "v2.4.7"
  pullPolicy: IfNotPresent

# These will override the name that is used for all resources.
# The name defaults to .Chart.Name and the fullname defaults to .Release.Name
nameOverride: ""
fullnameOverride: ""

ports:
  traefik:
    port: 8080
    protocol: TCP
  web:
    port: 80
    protocol: TCP

services:
  loadbalancer:
    serviceType: LoadBalancer
    ports:
      - web

serviceAccount:
  name: ""
