dashboardRoute:
  host: localhost

traefik:
  image:
    name: traefik
    # defaults to appVersion
    tag: "v2.4.7"
    pullPolicy: IfNotPresent

  deployment:
    enabled: true
    # Can be either Deployment or DaemonSet
    kind: DaemonSet

  # Use ingressClass. Ignored if Traefik version < 2.3 / kubernetes < 1.18.x
  ingressClass:
    enabled: true
    isDefaultClass: true

  service:
    enabled: true
    type: LoadBalancer
