image:
  name: traefik
  tag: "v2.4.7"
  pullPolicy: IfNotPresent

# These will override the name that is used for all resources.
# The name defaults to .Chart.Name and the fullname defaults to .Release.Name
nameOverride: ""
fullnameOverride: ""

# Configure ports. A service is only created if the port config has a serviceType
ports:
  traefik:
    port: 8080
    protocol: TCP
  web:
    serviceType: NodePort
    port: 80
    nodePort: 30080
    protocol: TCP
  websecure:
    serviceType: NodePort
    port: 443
    nodePort: 30443
    protocol: TCP
    tls:
      enabled: true



serviceAccount:
  name: ""
