image:
  name: traefik
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# Configure ports. A service is only created if the port config has a serviceType
ports:
  traefik:
    port: 8080
    protocol: TCP
  web:
    serviceType: NodePort
    port: 80
    nodePort: 32286
    protocol: TCP


serviceAccount:
  name: ""
