apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "mukube-ingress.fullname" . }}
  labels:
    {{- include "mukube-ingress.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mukube-ingress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mukube-ingress.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "mukube-ingress.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.name }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range $name, $config := .Values.ports }}
            - name: {{ $name }}
              containerPort: {{ $config.port }}
              protocol: {{ default "TCP" $config.protocol | quote }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.ports.traefik.port }}
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.ports.traefik.port }}
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          args:
            - "--api=true"
            - "--api.dashboard=true"
            - "--api.insecure=true"
            - "--ping=true"
            - "--providers.kubernetesingress=true"
            {{- range $name, $config := .Values.ports }}
            {{- if $config }}
            - "--entryPoints.{{$name}}.address=:{{ $config.port }}/{{ default "tcp" $config.protocol | lower }}"
            {{- end }}
            {{- end }}
