# The definitions in _helpers.tpl does not work in ranges because it changes the scope
{{- $fullname := include "mukube-ingress.fullname" . -}}
{{- $labels := include "mukube-ingress.labels" . -}}
{{- $selectorLabels := include "mukube-ingress.selectorLabels" . }}

{{- range $serviceName, $serviceConfig := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $serviceName }}
  labels:
    {{- $labels | nindent 8 }}
spec:
  type: {{ $serviceConfig.serviceType }}
  {{- if $serviceConfig.loadBalancerIP }}
  loadBalancerIP: {{ $serviceConfig.loadBalancerIP }}
  {{- end }}
  ports:
    {{- range $name := $serviceConfig.ports}}
      {{- if hasKey $.ports $name -}}
      {{- $config := get $.ports $name -}}
    - port: {{ $config.port }}
      name: {{ $name }}
      targetPort: {{ $name }}
      protocol: {{ default "TCP" $config.protocol | quote }}
      {{- end }}
    {{- end }}
  selector:
    {{- $selectorLabels | nindent 8 }}
{{- end }}
