name: Test the deployment of the ingress

on: pull_request

jobs:
  test-loadbalancer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        inputs:
          config: "test/kind.yaml"
      - name: Install Ingress
        run: helm install ingress chart --namespace ingress --create-namespace
      - name: Install Test Chart
        run: helm install test-app test/chart
